
name: SE-Poker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile executable
        run: sbt build

      # - name: Upload executable
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: se_poker
      #     path: target/scala-3.3.1/SE-Poker-assembly-0.1.0.jar

      - name: Run tests
        run: sbt clean coverage test
      
      - name: Generate coverage report
        run: sbt coverageReport

      - name: Aggregate coverage report
        run: sbt coverageAggregate
      
      - name: Upload coverage to coveralls.io
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: sbt coveralls
