
name: SE-Poker CI/CD

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test with scoverage
        run: sbt clean coverage test coverageReport
      
      - name: Aggregate coverage
        run: sbt coverageAggregate

      - name: Package with sbt-assembly
        run: sbt clean assembly

      - name: Upload executable jar
        uses: actions/upload-artifact@v2
        with:
          name: se_poker
          path: target/scala-3.3.1/SE-Poker-assembly-0.1.0.jar
      
      - name: Upload to coveralls
        run: sbt coveralls
